### PR TITLE
Feature/adjustments

### PR DESCRIPTION
**Pull request by RainbowDashLabs**
Make ILandLord a Plugin
This allows us to not make those dirty ILanlord#getPlugin() calls and allows us to directly call plugin methods.

Update gradle to 7.3 and java version to 11

Replace JavaPlugin with Plugin interface everywhere

None of these changes is breaking for now except the java version bump, but this is okay.

### CODE REVIEW

**Comment by Aurelien30000** [comment]
Please merge this now and I'll adapt my pr, some changes are required.

**Comment by RainbowDashLabs** [comment]
> Please merge this now and I'll adapt my pr, some changes are required.

Lets merge it into your pr. I gonna do a rebase on your branch

**Comment by RainbowDashLabs** [comment]
@Aurelien30000 have a look and if you agree you can merge it.

The branch is rebased and you wont have to change anything on your side.

**Comment by Aurelien30000** [comment]
Oh you did everything, thanks :D

**Pull request merged**
